[package]
name = "gitignore-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
include_dir = "0.7.3"
inquire = "0.6.2"
